<a href="https://colab.research.google.com/github/rldckd0103/pdm02/blob/master/numpy/numpy_3_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy
## random 서브모듈
> [데이터싸이언스 스쿨:난수발생](https://datascienceschool.net/view-notebook/8bf41f87a08b4c44b307799577736a28/)

In [2]:
import numpy as np

## 난수 생성
> NumPy의 random 서브모듈은 난수를 생성하는 다양한 명령을 제공.

- rand: 0부터 1사이의 균일 분포 (uniform distribution)
- randn: 가우시안 표준 정규 분포 (normal distribution, Gaussian)
- randint: 균일 분포의 정수 난수 (uniform int)

> randn()은 평균 0, 표준편차 1 인 가우시안 정규분포를 생성.

### rand: 0부터 1사이의 균일 분포 (uniform distribution)

In [3]:
np.random.rand(5)

array([0.86863654, 0.70479289, 0.63140971, 0.00672942, 0.37631855])

In [5]:
np.random.rand(3)

array([0.43922207, 0.30884904, 0.48585966])

### randn: 가우시안 표준 정규 분포 (normal distribution, Gaussian)

In [6]:
np.random.randn(5)

array([ 1.69644224, -0.65620237,  0.06061716, -2.26066487, -0.47384489])

### randint: 균일 분포의 정수 난수 (uniform int)
- numpy.random.randint(low, high=None, size=None, dtype='l')

In [26]:
np.random.randint(5)

2

In [19]:
np.random.randint(5,9) 

8

In [27]:
np.random.randint(0,10,5)

array([1, 6, 7, 5, 3])

In [28]:
np.random.randint(0,10,5)

array([3, 2, 6, 6, 8])

In [29]:
np.random.randint(0,10,6).reshape(2,3)

array([[1, 8, 9],
       [1, 3, 2]])

## 난수 생성 seed 설정
- numpy.random.seed(seed=None)
- np.random.seed(number)

In [38]:
np.random.seed()

In [39]:
np.random.rand(5)

array([0.66808006, 0.92764931, 0.50157723, 0.18672731, 0.2460203 ])

In [40]:
np.random.rand(5)

array([0.13278171, 0.55690749, 0.57544915, 0.42786494, 0.36776173])

### 동일한 무작위수 생성
- seed를 고정하고 무작위수 생성

In [43]:
np.random.seed(1234)

In [42]:
np.random.rand(5)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581])

In [44]:
np.random.seed(1234)

In [45]:
np.random.rand(5)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581])

### seed 고정 후에 randint(5)

In [46]:
np.random.seed(5678)
np.random.randint(1,10,5)

array([5, 8, 3, 5, 4])

In [47]:
np.random.randint(1,10,5)

array([6, 3, 7, 4, 1])

In [48]:
np.random.seed(5678)
np.random.randint(1,10,5)

array([5, 8, 3, 5, 4])

In [49]:
np.random.seed(5678)
np.random.randint(1,10,5)

array([5, 8, 3, 5, 4])

In [50]:
# seed 변경
np.random.seed(0)
np.random.randint(1,10,5)

array([6, 1, 4, 4, 8])

## 도전 코딩
- 생성된 마구잡이수를 조사하고 사용하기 

### [도전 1.] 0부터 9까지의 마구잡이 정수를 1000개 만들고 각 수의 빈도를 구하시오. 

In [55]:
# n1000=
n1000 = np.random.randint(0,10,1000)
# n1000

In [56]:
np.unique(n1000)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
# 각 수의 빈도
np.unique(n1000, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([104,  96,  99, 101, 103, 101, 108,  94,  92, 102]))

In [59]:
value,count = np.unique(n1000, return_counts=True)

In [60]:
value

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
count

array([104,  96,  99, 101, 103, 101, 108,  94,  92, 102])

### [도전 2.] 0부터 9까지의 마구잡이 정수를 1000개 만들고 각 수가 처음 출현하는 인덱스를 구하시오.
> 0이 처음 나타날 때의 인덱스, 1이 처음 나타날 때의 인덱스, ... 

In [71]:
# 각 수가 처음 출현하는 인덱스
value, index = np.unique(n1000, return_index=True)

In [72]:
value

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
index

array([ 2,  1,  6,  8, 16,  4, 10, 12,  0,  3])

In [74]:
n1000[0], n1000[1], n1000[2]

(8, 1, 0)

In [75]:
n1000[index]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### [도전 3.] seed를 1234로 고정하고, 위의 도전1,2를 다시 해보시오. 

In [64]:
np.random.seed(1234)

## python graphics
- matplotlib
> import matplotlib.pyplot as plt

### 무작위수 분포 그려보기

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(n1000,label=range(0,10), color='red')
# plt.show()

### [도전] 균일분포와 정규분포를 비교하는 그림을 그리시오.

In [ ]:
plt.hist(np.random.rand(1000))

In [ ]:
plt.hist(np.random.randn(1000))

In [ ]:
np.max(np.random.randn(1000))

In [ ]:
value, count= np.unique(n1000, return_counts=True)